#!/usr/bin/env bash
# Generated by Gemini

# Exit immediately if any command fails
set -e

echo "=== 1. Installing dependencies ==="
sudo apt update
sudo apt install -y build-essential cmake pkg-config \
  libasound2-dev libpulse-dev libx11-dev libxext-dev \
  libxrandr-dev libxcursor-dev libxi-dev libxkbcommon-dev \
  libwayland-dev libgbm-dev libxss-dev libxtst-dev \
  libxrender-dev libxcomposite-dev libxinerama-dev

echo "=== 2. Building and installing SDL3 ==="
if [ ! -d "SDL" ]; then
  git clone https://github.com/libsdl-org/SDL.git --depth 1
fi

# Clean previous build artifacts if they exist
rm -rf build_sdl3

cmake -S SDL -B build_sdl3 -DCMAKE_BUILD_TYPE=Release
cmake --build build_sdl3 --parallel
sudo cmake --install build_sdl3
sudo ldconfig

echo "=== 3. Compiling src/main.c ==="
gcc src/main.c -o test $(pkg-config --cflags --libs sdl3) -lm

echo "=== 4. Running test program ==="
./test
